In [1]:
import pandas as pd

df = pd.read_csv("Heart_Failure_Prediction_Dataset.csv")

In [2]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [3]:
df['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [4]:
df['RestingECG'].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [5]:
df['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [6]:
df.loc[df['Sex']=='M','Sex']=1
df.loc[df['Sex']=='F','Sex']=0
df['Sex'] = df['Sex'].astype('int')

In [7]:
df = pd.get_dummies(df)

In [8]:
df

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0.0,0,0,1,0,0,0,1,0,1,0,0,0,1
1,49,0,160,180,0,156,1.0,1,0,0,1,0,0,1,0,1,0,0,1,0
2,37,1,130,283,0,98,0.0,0,0,1,0,0,0,0,1,1,0,0,0,1
3,48,0,138,214,0,108,1.5,1,1,0,0,0,0,1,0,0,1,0,1,0
4,54,1,150,195,0,122,0.0,0,0,0,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,132,1.2,1,0,0,0,1,0,1,0,1,0,0,1,0
914,68,1,144,193,1,141,3.4,1,1,0,0,0,0,1,0,1,0,0,1,0
915,57,1,130,131,0,115,1.2,1,1,0,0,0,0,1,0,0,1,0,1,0
916,57,0,130,236,0,174,0.0,1,0,1,0,0,1,0,0,1,0,0,1,0
917,38,1,138,175,0,173,0.0,0,0,0,1,0,0,1,0,1,0,0,0,1

In [9]:
features = df.drop(['HeartDisease'], axis=1)
target = df['HeartDisease']

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=42, stratify=target)

In [11]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
from sklearn.svm import SVC

clf = SVC()
clf.fit(X_train_scaled, y_train)

SVC()

In [13]:
pred = clf.predict(X_test_scaled)

In [14]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy :",accuracy_score(y_test, pred))
print("Precision :",precision_score(y_test, pred))
print("Recall :",recall_score(y_test, pred))
print("F1 score :",f1_score(y_test, pred))

Accuracy : 0.8782608695652174
Precision : 0.8561151079136691
Recall : 0.937007874015748
F1 score : 0.8947368421052632

In [15]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, pred,labels=[1,0]))

[[119   8]
 [ 20  83]]